// Generated by tooling/to_neo4j.py.
// Neo4j expression of the local Directory Projection.

CREATE CONSTRAINT k_node_key IF NOT EXISTS
FOR (n:KNode)
REQUIRE n.key IS UNIQUE;

CREATE INDEX k_node_kind IF NOT EXISTS
FOR (n:KNode)
ON (n.kind);

CREATE CONSTRAINT contributor_id IF NOT EXISTS
FOR (c:Contributor)
REQUIRE c.id IS UNIQUE;

MERGE (n:KNode {key: "K"})
SET n.local_id = "K", n.kind = "T", n.title = "Knowledge", n.description = "Root topic for the Cohesian k-graph."
SET n:Topic;

MERGE (n:KNode {key: "T-computer-science"})
SET n.local_id = "T-computer-science", n.kind = "T", n.title = "Computer science", n.description = "Computation, functions, semantics, binders, networking, and mechanics."
SET n:Topic;

MERGE (n:KNode {key: "T-computer-science/L-composite"})
SET n.local_id = "L-composite", n.kind = "L", n.title = "Composite", n.description = "Binder patterns and the TLF corpus composite model."
SET n:Lecture;

MERGE (n:KNode {key: "T-computer-science/L-composite/F-01-carbon-binder"})
SET n.local_id = "F-01-carbon-binder", n.kind = "F", n.title = "Carbon Binder", n.description = "A common binder interface that generates many structures."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/L-composite/F-02-type-binder"})
SET n.local_id = "F-02-type-binder", n.kind = "F", n.title = "Type Binder", n.description = "Types as a composite binder surface."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/L-composite/F-03-query-binder"})
SET n.local_id = "F-03-query-binder", n.kind = "F", n.title = "Query Binder", n.description = "Query structure as a binder specialization."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/L-composite/F-04-TLF-composite"})
SET n.local_id = "F-04-TLF-composite", n.kind = "F", n.title = "TLF Composite", n.description = "Topic / Lecture / File composite pattern for a knowledge corpus."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/L-functions"})
SET n.local_id = "L-functions", n.kind = "L", n.title = "Functions", n.description = "Functions as bounded nodes — composition, execution, networks, and wrappers."
SET n:Lecture;

MERGE (n:KNode {key: "T-computer-science/L-functions/F-01-function"})
SET n.local_id = "F-01-function", n.kind = "F", n.title = "Functions", n.description = "One lens on functions as bounded executable nodes."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/L-functions/F-02-execution"})
SET n.local_id = "F-02-execution", n.kind = "F", n.title = "Execution", n.description = "Execution as the interface admitting many executable forms."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/L-functions/F-03-function-network"})
SET n.local_id = "F-03-function-network", n.kind = "F", n.title = "Function Network", n.description = "Pipelines, wrappers, and functions as graph structure."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/L-functions/F-04-function-natural-wrappers"})
SET n.local_id = "F-04-function-natural-wrappers", n.kind = "F", n.title = "Function Natural Wrappers", n.description = "Natural wrappers as reusable function boundaries."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/L-functions/Fd-function-orchestration"})
SET n.local_id = "Fd-function-orchestration", n.kind = "Fd", n.title = "Function Orchestration", n.description = "Internal process coordination behind a function boundary (draft)."
SET n:File:Draft;

MERGE (n:KNode {key: "T-computer-science/L-inference"})
SET n.local_id = "L-inference", n.kind = "L", n.title = "Inference", n.description = "Theorem-style reasoning, agents, and conclusions."
SET n:Lecture;

MERGE (n:KNode {key: "T-computer-science/L-inference/F-01-theorem"})
SET n.local_id = "F-01-theorem", n.kind = "F", n.title = "Inference Theorem", n.description = "Inducing a common semantic backbone from a family of input files."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/L-inference/F-02-agents"})
SET n.local_id = "F-02-agents", n.kind = "F", n.title = "Agent Architecture", n.description = "Agent structure for inference over semantic data."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/L-inference/F-03-conclusions"})
SET n.local_id = "F-03-conclusions", n.kind = "F", n.title = "Conclusions", n.description = "Conclusions from the inference exploration."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/L-semantics"})
SET n.local_id = "L-semantics", n.kind = "L", n.title = "Semantics", n.description = "Data semantics, JSON representation, and agent prompts."
SET n:Lecture;

MERGE (n:KNode {key: "T-computer-science/L-semantics/F-01-data-semantics"})
SET n.local_id = "F-01-data-semantics", n.kind = "F", n.title = "Data Semantics", n.description = "Composite tree shape of data before file format."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/L-semantics/F-02-json-representation"})
SET n.local_id = "F-02-json-representation", n.kind = "F", n.title = "JSON Representation", n.description = "JSON as a representation layer for semantic data."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/L-semantics/F-03-agent-prompt"})
SET n.local_id = "F-03-agent-prompt", n.kind = "F", n.title = "Semantic Data Packets", n.description = "Agent prompts and semantic data packets."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/T-mechanics"})
SET n.local_id = "T-mechanics", n.kind = "T", n.title = "Mechanics", n.description = "Computational mechanics and ticker-like systems."
SET n:Topic;

MERGE (n:KNode {key: "T-computer-science/T-mechanics/L-sparse-ticker-state"})
SET n.local_id = "L-sparse-ticker-state", n.kind = "L", n.title = "Sparse ticker state", n.description = "Sparse structures and ticker-like ledger systems."
SET n:Lecture;

MERGE (n:KNode {key: "T-computer-science/T-mechanics/L-sparse-ticker-state/F-sparse_ticker_state_ledger"})
SET n.local_id = "F-sparse_ticker_state_ledger", n.kind = "F", n.title = "Sparse Ticker State Ledger", n.description = "Tracking, replaying, and rolling back state in discrete animated worlds."
SET n:File;

MERGE (n:KNode {key: "T-computer-science/T-networking"})
SET n.local_id = "T-networking", n.kind = "T", n.title = "Networking", n.description = "Networks, naming, and resolution — trees with typed attachments."
SET n:Topic;

MERGE (n:KNode {key: "T-computer-science/T-networking/L-DNS"})
SET n.local_id = "L-DNS", n.kind = "L", n.title = "DNS", n.description = "Domain namespace tree, zones, and typed DNS record attachments."
SET n:Lecture;

MERGE (n:KNode {key: "T-computer-science/T-networking/L-DNS/F-01-introduction"})
SET n.local_id = "F-01-introduction", n.kind = "F", n.title = "Introduction", n.description = "Domain namespace tree, zones, and typed DNS record attachments."
SET n:File;

MERGE (n:KNode {key: "T-math"})
SET n.local_id = "T-math", n.kind = "T", n.title = "Math", n.description = "Mathematical explorations in the Cohesian k-graph."
SET n:Topic;

MERGE (n:KNode {key: "T-math/L-division"})
SET n.local_id = "L-division", n.kind = "L", n.title = "Division", n.description = "Division topics (in development)."
SET n:Lecture;

MERGE (n:KNode {key: "T-math/L-division/F-01-introduction"})
SET n.local_id = "F-01-introduction", n.kind = "F", n.title = "Introduction", n.description = "Division topics (work in progress)."
SET n:File;

MERGE (n:KNode {key: "T-math/L-exponential-phase"})
SET n.local_id = "L-exponential-phase", n.kind = "L", n.title = "Exponential phase", n.description = "Exponential growth, layers, and transformations as composable structures."
SET n:Lecture;

MERGE (n:KNode {key: "T-math/L-exponential-phase/F-01-branching-depth-resolution"})
SET n.local_id = "F-01-branching-depth-resolution", n.kind = "F", n.title = "Branching Depth Resolution", n.description = "Base as branching factor; exponent as depth coordinate."
SET n:File;

MERGE (n:KNode {key: "T-math/L-exponential-phase/F-02-discrete-phase-rulers"})
SET n.local_id = "F-02-discrete-phase-rulers", n.kind = "F", n.title = "Discrete Phase Rulers", n.description = "Phase rulers that inspect coarse exponential jumps without changing the base."
SET n:File;

MERGE (n:KNode {key: "T-math/L-exponential-phase/F-03-hidden-generators"})
SET n.local_id = "F-03-hidden-generators", n.kind = "F", n.title = "Hidden Generators", n.description = "When a phase step lands in the naturals, it becomes a new local branching base."
SET n:File;

MERGE (n:KNode {key: "T-math/L-exponential-phase/Fd-exponential-phase-visual-notebook"})
SET n.local_id = "Fd-exponential-phase-visual-notebook", n.kind = "Fd", n.title = "Exponential phase visual notebook", n.description = "Exponential phase visual notebook (draft)."
SET n:File:Draft;

MERGE (n:KNode {key: "T-math/T-linear-algebra"})
SET n.local_id = "T-linear-algebra", n.kind = "T", n.title = "Linear algebra", n.description = "Vector spaces, bases, and related structure."
SET n:Topic;

MERGE (n:KNode {key: "T-math/T-linear-algebra/T-vectors"})
SET n.local_id = "T-vectors", n.kind = "T", n.title = "Vectors", n.description = "Vector-space lectures under linear algebra."
SET n:Topic;

MERGE (n:KNode {key: "T-math/T-linear-algebra/T-vectors/L-basis"})
SET n.local_id = "L-basis", n.kind = "L", n.title = "Basis", n.description = "Basis and coordinates (in development)."
SET n:Lecture;

MERGE (n:KNode {key: "T-math/T-linear-algebra/T-vectors/L-basis/F-01-introduction"})
SET n.local_id = "F-01-introduction", n.kind = "F", n.title = "Introduction", n.description = "Basis and coordinates (work in progress)."
SET n:File;

MERGE (n:KNode {key: "T-math/T-linear-algebra/T-vectors/L-reflection"})
SET n.local_id = "L-reflection", n.kind = "L", n.title = "Reflection", n.description = "Reflections and symmetry in vector space (in development)."
SET n:Lecture;

MERGE (n:KNode {key: "T-math/T-linear-algebra/T-vectors/L-reflection/F-01-introduction"})
SET n.local_id = "F-01-introduction", n.kind = "F", n.title = "Introduction", n.description = "Reflections in vector space (work in progress)."
SET n:File;

MERGE (:Contributor {id: "research"});

MERGE (:Contributor {id: "studio"});

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "K"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-composite"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-composite/F-01-carbon-binder"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "studio"}), (n:KNode {key: "T-computer-science/L-composite/F-01-carbon-binder"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["py", "mp4", "youtube"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-composite/F-02-type-binder"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "studio"}), (n:KNode {key: "T-computer-science/L-composite/F-02-type-binder"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["py", "mp4", "youtube"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-composite/F-03-query-binder"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "studio"}), (n:KNode {key: "T-computer-science/L-composite/F-03-query-binder"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["py", "mp4", "youtube"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-composite/F-04-TLF-composite"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "studio"}), (n:KNode {key: "T-computer-science/L-composite/F-04-TLF-composite"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["py", "mp4", "youtube"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-functions"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-functions/F-01-function"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-functions/F-02-execution"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-functions/F-03-function-network"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-functions/F-04-function-natural-wrappers"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-functions/Fd-function-orchestration"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-inference"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-inference/F-01-theorem"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-inference/F-02-agents"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-inference/F-03-conclusions"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-semantics"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-semantics/F-01-data-semantics"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-semantics/F-02-json-representation"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/L-semantics/F-03-agent-prompt"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/T-mechanics"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/T-mechanics/L-sparse-ticker-state"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/T-mechanics/L-sparse-ticker-state/F-sparse_ticker_state_ledger"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md", "ipynb"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/T-networking"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/T-networking/L-DNS"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-computer-science/T-networking/L-DNS/F-01-introduction"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math/L-division"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math/L-division/F-01-introduction"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math/L-exponential-phase"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math/L-exponential-phase/F-01-branching-depth-resolution"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math/L-exponential-phase/F-02-discrete-phase-rulers"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math/L-exponential-phase/F-03-hidden-generators"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math/L-exponential-phase/Fd-exponential-phase-visual-notebook"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["ipynb"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math/T-linear-algebra"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math/T-linear-algebra/T-vectors"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math/T-linear-algebra/T-vectors/L-basis"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math/T-linear-algebra/T-vectors/L-basis/F-01-introduction"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math/T-linear-algebra/T-vectors/L-reflection"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = [];

MATCH (c:Contributor {id: "research"}), (n:KNode {key: "T-math/T-linear-algebra/T-vectors/L-reflection/F-01-introduction"})
MERGE (c)-[r:CONTRIBUTED]->(n)
SET r.formats = ["md"];

MATCH (a:KNode {key: "K"}), (b:KNode {key: "T-math"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "K"}), (b:KNode {key: "T-computer-science"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {key: "T-computer-science"}), (b:KNode {key: "T-computer-science/L-composite"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-computer-science"}), (b:KNode {key: "T-computer-science/L-functions"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {key: "T-computer-science"}), (b:KNode {key: "T-computer-science/L-inference"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {key: "T-computer-science"}), (b:KNode {key: "T-computer-science/L-semantics"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 3;

MATCH (a:KNode {key: "T-computer-science"}), (b:KNode {key: "T-computer-science/T-mechanics"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 4;

MATCH (a:KNode {key: "T-computer-science"}), (b:KNode {key: "T-computer-science/T-networking"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 5;

MATCH (a:KNode {key: "T-computer-science/L-composite"}), (b:KNode {key: "T-computer-science/L-composite/F-01-carbon-binder"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-computer-science/L-composite"}), (b:KNode {key: "T-computer-science/L-composite/F-02-type-binder"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {key: "T-computer-science/L-composite"}), (b:KNode {key: "T-computer-science/L-composite/F-03-query-binder"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {key: "T-computer-science/L-composite"}), (b:KNode {key: "T-computer-science/L-composite/F-04-TLF-composite"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 3;

MATCH (a:KNode {key: "T-computer-science/L-functions"}), (b:KNode {key: "T-computer-science/L-functions/F-01-function"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-computer-science/L-functions"}), (b:KNode {key: "T-computer-science/L-functions/F-02-execution"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {key: "T-computer-science/L-functions"}), (b:KNode {key: "T-computer-science/L-functions/F-03-function-network"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {key: "T-computer-science/L-functions"}), (b:KNode {key: "T-computer-science/L-functions/F-04-function-natural-wrappers"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 3;

MATCH (a:KNode {key: "T-computer-science/L-functions"}), (b:KNode {key: "T-computer-science/L-functions/Fd-function-orchestration"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 4;

MATCH (a:KNode {key: "T-computer-science/L-inference"}), (b:KNode {key: "T-computer-science/L-inference/F-01-theorem"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-computer-science/L-inference"}), (b:KNode {key: "T-computer-science/L-inference/F-02-agents"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {key: "T-computer-science/L-inference"}), (b:KNode {key: "T-computer-science/L-inference/F-03-conclusions"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {key: "T-computer-science/L-semantics"}), (b:KNode {key: "T-computer-science/L-semantics/F-01-data-semantics"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-computer-science/L-semantics"}), (b:KNode {key: "T-computer-science/L-semantics/F-02-json-representation"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {key: "T-computer-science/L-semantics"}), (b:KNode {key: "T-computer-science/L-semantics/F-03-agent-prompt"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {key: "T-computer-science/T-mechanics"}), (b:KNode {key: "T-computer-science/T-mechanics/L-sparse-ticker-state"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-computer-science/T-mechanics/L-sparse-ticker-state"}), (b:KNode {key: "T-computer-science/T-mechanics/L-sparse-ticker-state/F-sparse_ticker_state_ledger"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-computer-science/T-networking"}), (b:KNode {key: "T-computer-science/T-networking/L-DNS"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-computer-science/T-networking/L-DNS"}), (b:KNode {key: "T-computer-science/T-networking/L-DNS/F-01-introduction"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-math"}), (b:KNode {key: "T-math/L-division"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-math"}), (b:KNode {key: "T-math/L-exponential-phase"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {key: "T-math"}), (b:KNode {key: "T-math/T-linear-algebra"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {key: "T-math/L-division"}), (b:KNode {key: "T-math/L-division/F-01-introduction"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-math/L-exponential-phase"}), (b:KNode {key: "T-math/L-exponential-phase/F-01-branching-depth-resolution"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-math/L-exponential-phase"}), (b:KNode {key: "T-math/L-exponential-phase/F-02-discrete-phase-rulers"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {key: "T-math/L-exponential-phase"}), (b:KNode {key: "T-math/L-exponential-phase/F-03-hidden-generators"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {key: "T-math/L-exponential-phase"}), (b:KNode {key: "T-math/L-exponential-phase/Fd-exponential-phase-visual-notebook"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 3;

MATCH (a:KNode {key: "T-math/T-linear-algebra"}), (b:KNode {key: "T-math/T-linear-algebra/T-vectors"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-math/T-linear-algebra/T-vectors"}), (b:KNode {key: "T-math/T-linear-algebra/T-vectors/L-basis"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-math/T-linear-algebra/T-vectors"}), (b:KNode {key: "T-math/T-linear-algebra/T-vectors/L-reflection"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {key: "T-math/T-linear-algebra/T-vectors/L-basis"}), (b:KNode {key: "T-math/T-linear-algebra/T-vectors/L-basis/F-01-introduction"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-math/T-linear-algebra/T-vectors/L-reflection"}), (b:KNode {key: "T-math/T-linear-algebra/T-vectors/L-reflection/F-01-introduction"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {key: "T-computer-science/L-composite/F-01-carbon-binder"}), (b:KNode {key: "T-computer-science/L-composite/F-02-type-binder"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {key: "T-computer-science/L-composite/F-02-type-binder"}), (b:KNode {key: "T-computer-science/L-composite/F-03-query-binder"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {key: "T-computer-science/L-composite/F-03-query-binder"}), (b:KNode {key: "T-computer-science/L-composite/F-04-TLF-composite"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {key: "T-computer-science/L-functions/F-01-function"}), (b:KNode {key: "T-computer-science/L-functions/F-02-execution"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {key: "T-computer-science/L-functions/F-02-execution"}), (b:KNode {key: "T-computer-science/L-functions/F-03-function-network"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {key: "T-computer-science/L-functions/F-03-function-network"}), (b:KNode {key: "T-computer-science/L-functions/F-04-function-natural-wrappers"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {key: "T-computer-science/L-functions/F-04-function-natural-wrappers"}), (b:KNode {key: "T-computer-science/L-functions/Fd-function-orchestration"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {key: "T-computer-science/L-inference/F-01-theorem"}), (b:KNode {key: "T-computer-science/L-inference/F-02-agents"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {key: "T-computer-science/L-inference/F-02-agents"}), (b:KNode {key: "T-computer-science/L-inference/F-03-conclusions"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {key: "T-computer-science/L-semantics/F-01-data-semantics"}), (b:KNode {key: "T-computer-science/L-semantics/F-02-json-representation"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {key: "T-computer-science/L-semantics/F-02-json-representation"}), (b:KNode {key: "T-computer-science/L-semantics/F-03-agent-prompt"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {key: "T-math/L-exponential-phase/F-01-branching-depth-resolution"}), (b:KNode {key: "T-math/L-exponential-phase/F-02-discrete-phase-rulers"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {key: "T-math/L-exponential-phase/F-02-discrete-phase-rulers"}), (b:KNode {key: "T-math/L-exponential-phase/F-03-hidden-generators"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {key: "T-math/L-exponential-phase/F-03-hidden-generators"}), (b:KNode {key: "T-math/L-exponential-phase/Fd-exponential-phase-visual-notebook"})
MERGE (a)-[:NEXT]->(b);
