// Generated by tooling/to_neo4j.py.
// Neo4j expression of the local Directory Projection.

DROP CONSTRAINT k_node_path IF EXISTS;

CREATE CONSTRAINT k_node_id IF NOT EXISTS
FOR (n:KNode)
REQUIRE n.id IS UNIQUE;

CREATE INDEX k_node_kind IF NOT EXISTS
FOR (n:KNode)
ON (n.kind);

CREATE CONSTRAINT contributor_id IF NOT EXISTS
FOR (c:Contributor)
REQUIRE c.id IS UNIQUE;

MATCH (:Contributor)-[r:CONTRIBUTED]->(:KNode)
DELETE r;

MATCH (:Contributor)-[r:PROVIDES]->(:KNode)
DELETE r;

MATCH (n:KNode)
REMOVE n.path;

MERGE (n:KNode {id: "563523fd-87cd-41c4-a0f6-00b54f0f7bdd"})
SET n.local_id = "K", n.kind = "T", n.title = "Knowledge", n.description = "Root topic for the Cohesian k-graph."
SET n:Topic;

MERGE (n:KNode {id: "3a639722-8594-4c6c-9527-ffddd25cf2ec"})
SET n.local_id = "T-computer-science", n.kind = "T", n.title = "Computer science", n.description = "Computation, functions, semantics, binders, networking, and mechanics."
SET n:Topic;

MERGE (n:KNode {id: "dfa7000b-4b6b-480a-9a33-90d7d5f764c5"})
SET n.local_id = "L-composite", n.kind = "L", n.title = "Composite", n.description = "Binder patterns and the TLF corpus composite model."
SET n:Lecture;

MERGE (n:KNode {id: "2a05068f-d48c-4fdd-915c-778bc8f42211"})
SET n.local_id = "F-01-carbon-binder", n.kind = "F", n.title = "Carbon Binder", n.description = "A common binder interface that generates many structures."
SET n:File;

MERGE (n:KNode {id: "24309c9a-2e80-47b9-884b-cc9801178c0d"})
SET n.local_id = "F-02-type-binder", n.kind = "F", n.title = "Type Binder", n.description = "Types as a composite binder surface."
SET n:File;

MERGE (n:KNode {id: "371342c0-401f-4d34-a537-439386bf9f7c"})
SET n.local_id = "F-03-query-binder", n.kind = "F", n.title = "Query Binder", n.description = "Query structure as a binder specialization."
SET n:File;

MERGE (n:KNode {id: "42292902-3874-4d54-87ec-0e1b7362af13"})
SET n.local_id = "F-04-TLF-composite", n.kind = "F", n.title = "TLF Composite", n.description = "Topic / Lecture / File composite pattern for a knowledge corpus."
SET n:File;

MERGE (n:KNode {id: "d9cc0386-2ec5-4b6f-be72-24e75594598d"})
SET n.local_id = "L-functions", n.kind = "L", n.title = "Functions", n.description = "Functions as bounded nodes — composition, execution, networks, and wrappers."
SET n:Lecture;

MERGE (n:KNode {id: "499ff1af-eed7-425d-9fed-e357ec2e0b97"})
SET n.local_id = "F-01-function", n.kind = "F", n.title = "Functions", n.description = "One lens on functions as bounded executable nodes."
SET n:File;

MERGE (n:KNode {id: "9d406912-c737-416c-94f2-4edb90db3ee7"})
SET n.local_id = "F-02-execution", n.kind = "F", n.title = "Execution", n.description = "Execution as the interface admitting many executable forms."
SET n:File;

MERGE (n:KNode {id: "1e650360-f987-42c8-ab37-d2e928b82b32"})
SET n.local_id = "F-03-function-network", n.kind = "F", n.title = "Function Network", n.description = "Pipelines, wrappers, and functions as graph structure."
SET n:File;

MERGE (n:KNode {id: "7bd2455a-1fe5-4972-9c36-78d6a4f0df9b"})
SET n.local_id = "F-04-function-natural-wrappers", n.kind = "F", n.title = "Function Natural Wrappers", n.description = "Natural wrappers as reusable function boundaries."
SET n:File;

MERGE (n:KNode {id: "9e9629bd-eb94-40fc-ba6e-922420cd13f7"})
SET n.local_id = "Fd-function-orchestration", n.kind = "Fd", n.title = "Function Orchestration", n.description = "Internal process coordination behind a function boundary (draft)."
SET n:File:Draft;

MERGE (n:KNode {id: "da255734-d513-41e4-b64c-721403e9da50"})
SET n.local_id = "L-inference", n.kind = "L", n.title = "Inference", n.description = "Theorem-style reasoning, agents, and conclusions."
SET n:Lecture;

MERGE (n:KNode {id: "f776b280-d6fa-4bbd-b213-4978165137eb"})
SET n.local_id = "F-01-theorem", n.kind = "F", n.title = "Inference Theorem", n.description = "Inducing a common semantic backbone from a family of input files."
SET n:File;

MERGE (n:KNode {id: "08113955-1ff0-4131-877e-4466e614bd1b"})
SET n.local_id = "F-02-agents", n.kind = "F", n.title = "Agent Architecture", n.description = "Agent structure for inference over semantic data."
SET n:File;

MERGE (n:KNode {id: "bb00a29b-d851-4395-9e20-bce895bb379e"})
SET n.local_id = "F-03-conclusions", n.kind = "F", n.title = "Conclusions", n.description = "Conclusions from the inference exploration."
SET n:File;

MERGE (n:KNode {id: "804dadca-9f14-44c8-884c-d3921f9c60e6"})
SET n.local_id = "L-semantics", n.kind = "L", n.title = "Semantics", n.description = "Data semantics, JSON representation, and agent prompts."
SET n:Lecture;

MERGE (n:KNode {id: "39b82207-e234-4352-bc3c-01d84362a7eb"})
SET n.local_id = "F-01-data-semantics", n.kind = "F", n.title = "Data Semantics", n.description = "Composite tree shape of data before file format."
SET n:File;

MERGE (n:KNode {id: "5da0c374-473b-40d6-a7dd-659dc4f5211d"})
SET n.local_id = "F-02-json-representation", n.kind = "F", n.title = "JSON Representation", n.description = "JSON as a representation layer for semantic data."
SET n:File;

MERGE (n:KNode {id: "0fa7348d-69f2-487a-a684-71eada16a96d"})
SET n.local_id = "F-03-agent-prompt", n.kind = "F", n.title = "Semantic Data Packets", n.description = "Agent prompts and semantic data packets."
SET n:File;

MERGE (n:KNode {id: "e6217c42-963a-4fbf-9e0a-f224cb826639"})
SET n.local_id = "T-mechanics", n.kind = "T", n.title = "Mechanics", n.description = "Computational mechanics and ticker-like systems."
SET n:Topic;

MERGE (n:KNode {id: "30f3686f-55a9-448c-858d-98f7d28be603"})
SET n.local_id = "L-sparse-ticker-state", n.kind = "L", n.title = "Sparse ticker state", n.description = "Sparse structures and ticker-like ledger systems."
SET n:Lecture;

MERGE (n:KNode {id: "ff73c9d4-922b-471e-beb5-3dde7c4a415f"})
SET n.local_id = "F-sparse_ticker_state_ledger", n.kind = "F", n.title = "Sparse Ticker State Ledger", n.description = "Tracking, replaying, and rolling back state in discrete animated worlds."
SET n:File;

MERGE (n:KNode {id: "efc84fce-0236-4141-b12d-24342b0d91ae"})
SET n.local_id = "T-networking", n.kind = "T", n.title = "Networking", n.description = "Networks, naming, and resolution — trees with typed attachments."
SET n:Topic;

MERGE (n:KNode {id: "e88a1fa1-2f6e-4004-94d6-b4c24ad7b8f1"})
SET n.local_id = "L-DNS", n.kind = "L", n.title = "DNS", n.description = "Domain namespace tree, zones, and typed DNS record attachments."
SET n:Lecture;

MERGE (n:KNode {id: "f2b1b8c2-86c8-484c-bb44-92c711ac607e"})
SET n.local_id = "F-01-introduction", n.kind = "F", n.title = "Introduction", n.description = "Domain namespace tree, zones, and typed DNS record attachments."
SET n:File;

MERGE (n:KNode {id: "61def28d-378b-421d-bd96-42281ecc5570"})
SET n.local_id = "T-math", n.kind = "T", n.title = "Math", n.description = "Mathematical explorations in the Cohesian k-graph."
SET n:Topic;

MERGE (n:KNode {id: "2c3cfe88-3010-4730-87b9-31138b863178"})
SET n.local_id = "L-division", n.kind = "L", n.title = "Division", n.description = "Division topics (in development)."
SET n:Lecture;

MERGE (n:KNode {id: "ff647a5d-44f0-42af-9f01-abcadd04fb37"})
SET n.local_id = "F-01-introduction", n.kind = "F", n.title = "Introduction", n.description = "Division topics (work in progress)."
SET n:File;

MERGE (n:KNode {id: "5a761f46-a4a4-4453-98a4-c0424f94aafc"})
SET n.local_id = "L-exponential-phase", n.kind = "L", n.title = "Exponential phase", n.description = "Exponential growth, layers, and transformations as composable structures."
SET n:Lecture;

MERGE (n:KNode {id: "1497eefc-aa3d-4444-a426-9ccb0410b0bf"})
SET n.local_id = "F-01-branching-depth-resolution", n.kind = "F", n.title = "Branching Depth Resolution", n.description = "Base as branching factor; exponent as depth coordinate."
SET n:File;

MERGE (n:KNode {id: "ff7c99b6-ce1f-4973-9d3c-89f1f12a1f69"})
SET n.local_id = "F-02-discrete-phase-rulers", n.kind = "F", n.title = "Discrete Phase Rulers", n.description = "Phase rulers that inspect coarse exponential jumps without changing the base."
SET n:File;

MERGE (n:KNode {id: "f1504ef9-d65e-4753-8032-27672b2ffa6a"})
SET n.local_id = "F-03-hidden-generators", n.kind = "F", n.title = "Hidden Generators", n.description = "When a phase step lands in the naturals, it becomes a new local branching base."
SET n:File;

MERGE (n:KNode {id: "c6d131b8-0ba5-4ab4-bfdb-c871b95b98e6"})
SET n.local_id = "Fd-exponential-phase-visual-notebook", n.kind = "Fd", n.title = "Exponential phase visual notebook", n.description = "Exponential phase visual notebook (draft)."
SET n:File:Draft;

MERGE (n:KNode {id: "37988c21-5843-4b3e-84ac-e80b338f0322"})
SET n.local_id = "T-linear-algebra", n.kind = "T", n.title = "Linear algebra", n.description = "Vector spaces, bases, and related structure."
SET n:Topic;

MERGE (n:KNode {id: "ae514a05-eb83-4013-a8c9-b1aaab27100b"})
SET n.local_id = "T-vectors", n.kind = "T", n.title = "Vectors", n.description = "Vector-space lectures under linear algebra."
SET n:Topic;

MERGE (n:KNode {id: "47a4d65e-41fe-4026-b87c-11050d29bacd"})
SET n.local_id = "L-basis", n.kind = "L", n.title = "Basis", n.description = "Basis and coordinates (in development)."
SET n:Lecture;

MERGE (n:KNode {id: "edba87bc-3359-4ea1-bfb7-7bb5d4762963"})
SET n.local_id = "F-01-introduction", n.kind = "F", n.title = "Introduction", n.description = "Basis and coordinates (work in progress)."
SET n:File;

MERGE (n:KNode {id: "2a9874d9-5c7e-414f-8959-1364f177aa84"})
SET n.local_id = "L-reflection", n.kind = "L", n.title = "Reflection", n.description = "Reflections and symmetry in vector space (in development)."
SET n:Lecture;

MERGE (n:KNode {id: "07ff1a0b-e84f-40bb-996f-467a03d2bf3c"})
SET n.local_id = "F-01-introduction", n.kind = "F", n.title = "Introduction", n.description = "Reflections in vector space (work in progress)."
SET n:File;

MERGE (n:KNode {id: "d46fb5c1-449d-4561-a399-93d8ec8b543f"})
SET n.local_id = "T-physics", n.kind = "T", n.title = "Physics", n.description = "Physical models, experiments, and observations across scales."
SET n:Topic;

MERGE (n:KNode {id: "1bdc520d-6211-4371-8ff0-2e7b3041aea4"})
SET n.local_id = "L-emergence", n.kind = "L", n.title = "Emergence", n.description = "How local interactions produce observable collective structure."
SET n:Lecture;

MERGE (n:KNode {id: "04475552-1433-4e6d-92f9-a44406c7ed18"})
SET n.local_id = "L-patchy-particle-emergence", n.kind = "L", n.title = "Patchy-particle Emergence", n.description = "A controlled particle study connecting local rules to macroscopic observables."
SET n:Lecture;

MERGE (n:KNode {id: "440e4d3d-ea9f-4915-97e6-2b6b7c09c6c4"})
SET n.local_id = "F-00-purpose-and-boundary", n.kind = "F", n.title = "Emergence from Local Rules to Global Observation", n.description = "Purpose, scope, and evidential boundary of the emergence study."
SET n:File;

MERGE (n:KNode {id: "579fa81e-4a5a-4521-98d9-ea8b69a48e8d"})
SET n.local_id = "F-01-microscopic-model", n.kind = "F", n.title = "The Patchy-particle Model", n.description = "Reduced-unit geometry, dynamics, interactions, and boundary conditions."
SET n:File;

MERGE (n:KNode {id: "65cecd50-0570-42ca-bf41-6b5ad967a0cf"})
SET n.local_id = "F-02-local-rules-and-parameters", n.kind = "F", n.title = "Local Rules and the Controlled Experiment", n.description = "Microscopic rules, control axes, and declared experimental parameters."
SET n:File;

MERGE (n:KNode {id: "d01f2da8-c079-4665-b0cf-cd78f5c9727e"})
SET n.local_id = "F-03-macroscopic-observables", n.kind = "F", n.title = "From Trajectories to Macroscopic Observables", n.description = "Contact-graph projection and ensemble observables derived from trajectories."
SET n:File;

MERGE (n:KNode {id: "6281d965-093e-4aaa-9ce0-2f67b95c8bbc"})
SET n.local_id = "F-04-experimental-laboratory", n.kind = "F", n.title = "Experimental Laboratory", n.description = "Reproducible HOOMD-blue experiment, notebook, and rendered trajectory."
SET n:File;

MERGE (n:KNode {id: "508419e1-a1ea-4863-82b7-3636e39e5ee4"})
SET n.local_id = "F-05-findings-and-limitations", n.kind = "F", n.title = "Findings and Limitations", n.description = "Supported observations, uncertainty, limitations, and next experiments."
SET n:File;

MERGE (:Contributor {id: "research"});

MERGE (:Contributor {id: "studio"});

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "2a05068f-d48c-4fdd-915c-778bc8f42211"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "57b3119069e3ac0a81a3384daed94cf076209b26b3c9eba9b9c943166ba51c00";

MATCH (c:Contributor {id: "studio"}), (n:KNode {id: "2a05068f-d48c-4fdd-915c-778bc8f42211"})
MERGE (c)-[r:PROVIDES {hierarchy: ["scenes"], key: "loci-project"}]->(n)
SET r.protocol = "loci-project@1", r.sha256 = "f576e6afd1f2013c99b97190a1d6cf10b7b25162728eec41260270a06b6e185c";

MATCH (c:Contributor {id: "studio"}), (n:KNode {id: "2a05068f-d48c-4fdd-915c-778bc8f42211"})
MERGE (c)-[r:PROVIDES {hierarchy: ["videos"], key: "mp4"}]->(n)
SET r.protocol = "mp4-file@1", r.sha256 = "71a89456adec6f26dda3282f93382076de615e36e276f53ed169d74e28d8ddb0";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "24309c9a-2e80-47b9-884b-cc9801178c0d"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "6f83353e4560651dd1f6db2b7367075807fe5b3527b1cd92098ca4b0d4978854";

MATCH (c:Contributor {id: "studio"}), (n:KNode {id: "24309c9a-2e80-47b9-884b-cc9801178c0d"})
MERGE (c)-[r:PROVIDES {hierarchy: ["scenes"], key: "loci-project"}]->(n)
SET r.protocol = "loci-project@1", r.sha256 = "3993a04963ceb95fcbbc713fe57e235d06485a2155ae5683b36b18c7c2d024a3";

MATCH (c:Contributor {id: "studio"}), (n:KNode {id: "24309c9a-2e80-47b9-884b-cc9801178c0d"})
MERGE (c)-[r:PROVIDES {hierarchy: ["videos"], key: "mp4"}]->(n)
SET r.protocol = "mp4-file@1", r.sha256 = "286fc32045a34e29b4982f916f234232ee90ef9607d291d6836df45a221e20d1";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "371342c0-401f-4d34-a537-439386bf9f7c"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "48aca6acaf797ff25abc7211572140f46f26a9a7fc59fe70785ce968ad576f3d";

MATCH (c:Contributor {id: "studio"}), (n:KNode {id: "371342c0-401f-4d34-a537-439386bf9f7c"})
MERGE (c)-[r:PROVIDES {hierarchy: ["scenes"], key: "loci-project"}]->(n)
SET r.protocol = "loci-project@1", r.sha256 = "c5b02d81ae3d1620ebc3eac982baeb5b64266196baa07408afe7d745f91b4445";

MATCH (c:Contributor {id: "studio"}), (n:KNode {id: "371342c0-401f-4d34-a537-439386bf9f7c"})
MERGE (c)-[r:PROVIDES {hierarchy: ["videos"], key: "mp4"}]->(n)
SET r.protocol = "mp4-file@1", r.sha256 = "a4f76cac042ea194965181e08b4943f96d0338106c19964c6ebb714d6eda7bbb";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "42292902-3874-4d54-87ec-0e1b7362af13"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "ac55bcff9acabcc2ed7890fa572edc06fc260212956043e9bc0a7278884d4c5e";

MATCH (c:Contributor {id: "studio"}), (n:KNode {id: "42292902-3874-4d54-87ec-0e1b7362af13"})
MERGE (c)-[r:PROVIDES {hierarchy: ["scenes"], key: "loci-project"}]->(n)
SET r.protocol = "loci-project@1", r.sha256 = "42d070e8479cc2ffee5fccad32a5aa6cbd6ccbccf1bd426f4a1c609a1b53dd42";

MATCH (c:Contributor {id: "studio"}), (n:KNode {id: "42292902-3874-4d54-87ec-0e1b7362af13"})
MERGE (c)-[r:PROVIDES {hierarchy: ["videos"], key: "mp4"}]->(n)
SET r.protocol = "mp4-file@1", r.sha256 = "e24ad15c57fcb90156b5aaa0b461218bfdf1b587cfa4529cc124bdddad0e1294";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "499ff1af-eed7-425d-9fed-e357ec2e0b97"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "aaacecaa42528397cc3cca3c88141863d7f381a50bec28bdacf6492dc1472386";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "9d406912-c737-416c-94f2-4edb90db3ee7"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "f0ea980f00faf605b704dda44044d77a4cb6276cd754da98150068589a2ce641";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "1e650360-f987-42c8-ab37-d2e928b82b32"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "f28b62124e8521afbfe722579a013052109a91a6923d5869fa3b9c6dd75e753d";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "7bd2455a-1fe5-4972-9c36-78d6a4f0df9b"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "cab090f6e9589ae52fb84276a527218df3ae925a75f8faea3d8d738323f498a8";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "9e9629bd-eb94-40fc-ba6e-922420cd13f7"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "bccf5bc84d685f710a4037d539c7e7b0991f34f6da7e34c501c0e8c5947e5d69";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "f776b280-d6fa-4bbd-b213-4978165137eb"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "fd6042869f969d29e491ab7131d881697404be9593315e518de5ebc9e8a15938";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "08113955-1ff0-4131-877e-4466e614bd1b"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "1ba23fb01fba33acf2e515d796b9ee803f662ce0e864f2d0726443a3fc7a762f";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "bb00a29b-d851-4395-9e20-bce895bb379e"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "91c23f04317a3bcbef9d90948c491a4c9342dc156f78784aca55346f2f9dcf31";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "39b82207-e234-4352-bc3c-01d84362a7eb"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "473a11a548b6cf1e09d3ce2b222e0a02635bc4bb9801508dc9f2f8bcdf31f259";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "5da0c374-473b-40d6-a7dd-659dc4f5211d"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "8e1aa0172a3f21d8a88ebec00f2dfb261d754efa1ac16d4ad968585c1cecdd69";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "0fa7348d-69f2-487a-a684-71eada16a96d"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "62ebb329955bdd27158918b1eb76ca87aac7656c6cc9e063ef2ff8195126bfdc";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "ff73c9d4-922b-471e-beb5-3dde7c4a415f"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "ipynb"}]->(n)
SET r.protocol = "jupyter-notebook-file@1", r.sha256 = "95f81c60107724ecbd84806466ff48a7883e581d82882dd988c86db16fc54136";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "ff73c9d4-922b-471e-beb5-3dde7c4a415f"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "9dfffb2d7135825abd9dc41b5eaef698a09eb39d028c74ec9588f68f530c8a4e";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "f2b1b8c2-86c8-484c-bb44-92c711ac607e"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "c5588b909ea1117d8bbb73acef1a2d9ee76117b4f4b30c305f818e5c8d6091dd";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "ff647a5d-44f0-42af-9f01-abcadd04fb37"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "63e9592b7d4a6d723647c6071bcdac5553232e1e31e4a8dd73df68a12d35a5c3";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "1497eefc-aa3d-4444-a426-9ccb0410b0bf"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "1d93b58e1a311b0910886a0d04ff843c48ba681dc3e51627dd4f67a1e40ddd98";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "ff7c99b6-ce1f-4973-9d3c-89f1f12a1f69"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "67188fb7e37a0c1eb0bb034e3398843908c90cf1e84be0a69a07c2247bddb141";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "f1504ef9-d65e-4753-8032-27672b2ffa6a"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "2f75a818a6a4349e1f96c821aa9bef11c6eaf11d7cbc1ea784ecece286b2687a";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "c6d131b8-0ba5-4ab4-bfdb-c871b95b98e6"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "ipynb"}]->(n)
SET r.protocol = "jupyter-notebook-file@1", r.sha256 = "4c177a1f56637d9715652df28902f98244291e2973d383e2e78448041d56a870";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "edba87bc-3359-4ea1-bfb7-7bb5d4762963"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "63e9592b7d4a6d723647c6071bcdac5553232e1e31e4a8dd73df68a12d35a5c3";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "07ff1a0b-e84f-40bb-996f-467a03d2bf3c"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "63e9592b7d4a6d723647c6071bcdac5553232e1e31e4a8dd73df68a12d35a5c3";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "440e4d3d-ea9f-4915-97e6-2b6b7c09c6c4"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "820e6e7f12c18ad02629e143c66ef3f5ecb5738aee663e66e0d22198a4bb85cb";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "579fa81e-4a5a-4521-98d9-ea8b69a48e8d"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "6ef42cc9793fec56f85bd59632c07fe50638efc1f25af9f7e79e0bdd92a2488d";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "65cecd50-0570-42ca-bf41-6b5ad967a0cf"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "232d9cda944583ab77d7e1ecd40610be6dcc41a81c55bc39ccf124b38a1b4544";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "d01f2da8-c079-4665-b0cf-cd78f5c9727e"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "6f63aa67de4a6b86b5d7b051d4bf09d03d81319a846ca784a06aaf7069eee1d5";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "6281d965-093e-4aaa-9ce0-2f67b95c8bbc"})
MERGE (c)-[r:PROVIDES {hierarchy: ["code"], key: "hoomd"}]->(n)
SET r.protocol = "python-project@1", r.sha256 = "54afb496c757d0e0434686dd85ecf7464cba6b24253607e3e79caf710eae5285";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "6281d965-093e-4aaa-9ce0-2f67b95c8bbc"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "ipynb"}]->(n)
SET r.protocol = "jupyter-notebook-file@1", r.sha256 = "0a870281e08909b4552c16b106f34425e78e203a3d53c7483a088f0a830760de";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "6281d965-093e-4aaa-9ce0-2f67b95c8bbc"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-bundle@1", r.sha256 = "a62a9391a6e2bc341aaf68ee5ef0307d9f0c73a0a2648aabd5766be51b70df26";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "6281d965-093e-4aaa-9ce0-2f67b95c8bbc"})
MERGE (c)-[r:PROVIDES {hierarchy: ["media"], key: "emergence-video"}]->(n)
SET r.protocol = "mp4-file@1", r.sha256 = "1a233fd8f919d8a2bc3251c477c1d96f42d3a5f31af4ff626c9c254e8eb6dc7e";

MATCH (c:Contributor {id: "research"}), (n:KNode {id: "508419e1-a1ea-4863-82b7-3636e39e5ee4"})
MERGE (c)-[r:PROVIDES {hierarchy: ["documents"], key: "md"}]->(n)
SET r.protocol = "markdown-file@1", r.sha256 = "4fe07d68bc33fae4d5458eb1a06928ab4ce52962361d6c968cdda5b5dd6cfb38";

MATCH (a:KNode {id: "563523fd-87cd-41c4-a0f6-00b54f0f7bdd"}), (b:KNode {id: "61def28d-378b-421d-bd96-42281ecc5570"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "563523fd-87cd-41c4-a0f6-00b54f0f7bdd"}), (b:KNode {id: "3a639722-8594-4c6c-9527-ffddd25cf2ec"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {id: "563523fd-87cd-41c4-a0f6-00b54f0f7bdd"}), (b:KNode {id: "d46fb5c1-449d-4561-a399-93d8ec8b543f"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {id: "3a639722-8594-4c6c-9527-ffddd25cf2ec"}), (b:KNode {id: "dfa7000b-4b6b-480a-9a33-90d7d5f764c5"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "3a639722-8594-4c6c-9527-ffddd25cf2ec"}), (b:KNode {id: "d9cc0386-2ec5-4b6f-be72-24e75594598d"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {id: "3a639722-8594-4c6c-9527-ffddd25cf2ec"}), (b:KNode {id: "da255734-d513-41e4-b64c-721403e9da50"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {id: "3a639722-8594-4c6c-9527-ffddd25cf2ec"}), (b:KNode {id: "804dadca-9f14-44c8-884c-d3921f9c60e6"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 3;

MATCH (a:KNode {id: "3a639722-8594-4c6c-9527-ffddd25cf2ec"}), (b:KNode {id: "e6217c42-963a-4fbf-9e0a-f224cb826639"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 4;

MATCH (a:KNode {id: "3a639722-8594-4c6c-9527-ffddd25cf2ec"}), (b:KNode {id: "efc84fce-0236-4141-b12d-24342b0d91ae"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 5;

MATCH (a:KNode {id: "dfa7000b-4b6b-480a-9a33-90d7d5f764c5"}), (b:KNode {id: "2a05068f-d48c-4fdd-915c-778bc8f42211"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "dfa7000b-4b6b-480a-9a33-90d7d5f764c5"}), (b:KNode {id: "24309c9a-2e80-47b9-884b-cc9801178c0d"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {id: "dfa7000b-4b6b-480a-9a33-90d7d5f764c5"}), (b:KNode {id: "371342c0-401f-4d34-a537-439386bf9f7c"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {id: "dfa7000b-4b6b-480a-9a33-90d7d5f764c5"}), (b:KNode {id: "42292902-3874-4d54-87ec-0e1b7362af13"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 3;

MATCH (a:KNode {id: "d9cc0386-2ec5-4b6f-be72-24e75594598d"}), (b:KNode {id: "499ff1af-eed7-425d-9fed-e357ec2e0b97"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "d9cc0386-2ec5-4b6f-be72-24e75594598d"}), (b:KNode {id: "9d406912-c737-416c-94f2-4edb90db3ee7"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {id: "d9cc0386-2ec5-4b6f-be72-24e75594598d"}), (b:KNode {id: "1e650360-f987-42c8-ab37-d2e928b82b32"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {id: "d9cc0386-2ec5-4b6f-be72-24e75594598d"}), (b:KNode {id: "7bd2455a-1fe5-4972-9c36-78d6a4f0df9b"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 3;

MATCH (a:KNode {id: "d9cc0386-2ec5-4b6f-be72-24e75594598d"}), (b:KNode {id: "9e9629bd-eb94-40fc-ba6e-922420cd13f7"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 4;

MATCH (a:KNode {id: "da255734-d513-41e4-b64c-721403e9da50"}), (b:KNode {id: "f776b280-d6fa-4bbd-b213-4978165137eb"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "da255734-d513-41e4-b64c-721403e9da50"}), (b:KNode {id: "08113955-1ff0-4131-877e-4466e614bd1b"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {id: "da255734-d513-41e4-b64c-721403e9da50"}), (b:KNode {id: "bb00a29b-d851-4395-9e20-bce895bb379e"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {id: "804dadca-9f14-44c8-884c-d3921f9c60e6"}), (b:KNode {id: "39b82207-e234-4352-bc3c-01d84362a7eb"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "804dadca-9f14-44c8-884c-d3921f9c60e6"}), (b:KNode {id: "5da0c374-473b-40d6-a7dd-659dc4f5211d"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {id: "804dadca-9f14-44c8-884c-d3921f9c60e6"}), (b:KNode {id: "0fa7348d-69f2-487a-a684-71eada16a96d"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {id: "e6217c42-963a-4fbf-9e0a-f224cb826639"}), (b:KNode {id: "30f3686f-55a9-448c-858d-98f7d28be603"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "30f3686f-55a9-448c-858d-98f7d28be603"}), (b:KNode {id: "ff73c9d4-922b-471e-beb5-3dde7c4a415f"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "efc84fce-0236-4141-b12d-24342b0d91ae"}), (b:KNode {id: "e88a1fa1-2f6e-4004-94d6-b4c24ad7b8f1"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "e88a1fa1-2f6e-4004-94d6-b4c24ad7b8f1"}), (b:KNode {id: "f2b1b8c2-86c8-484c-bb44-92c711ac607e"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "61def28d-378b-421d-bd96-42281ecc5570"}), (b:KNode {id: "2c3cfe88-3010-4730-87b9-31138b863178"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "61def28d-378b-421d-bd96-42281ecc5570"}), (b:KNode {id: "5a761f46-a4a4-4453-98a4-c0424f94aafc"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {id: "61def28d-378b-421d-bd96-42281ecc5570"}), (b:KNode {id: "37988c21-5843-4b3e-84ac-e80b338f0322"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {id: "2c3cfe88-3010-4730-87b9-31138b863178"}), (b:KNode {id: "ff647a5d-44f0-42af-9f01-abcadd04fb37"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "5a761f46-a4a4-4453-98a4-c0424f94aafc"}), (b:KNode {id: "1497eefc-aa3d-4444-a426-9ccb0410b0bf"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "5a761f46-a4a4-4453-98a4-c0424f94aafc"}), (b:KNode {id: "ff7c99b6-ce1f-4973-9d3c-89f1f12a1f69"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {id: "5a761f46-a4a4-4453-98a4-c0424f94aafc"}), (b:KNode {id: "f1504ef9-d65e-4753-8032-27672b2ffa6a"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {id: "5a761f46-a4a4-4453-98a4-c0424f94aafc"}), (b:KNode {id: "c6d131b8-0ba5-4ab4-bfdb-c871b95b98e6"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 3;

MATCH (a:KNode {id: "37988c21-5843-4b3e-84ac-e80b338f0322"}), (b:KNode {id: "ae514a05-eb83-4013-a8c9-b1aaab27100b"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "ae514a05-eb83-4013-a8c9-b1aaab27100b"}), (b:KNode {id: "47a4d65e-41fe-4026-b87c-11050d29bacd"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "ae514a05-eb83-4013-a8c9-b1aaab27100b"}), (b:KNode {id: "2a9874d9-5c7e-414f-8959-1364f177aa84"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {id: "47a4d65e-41fe-4026-b87c-11050d29bacd"}), (b:KNode {id: "edba87bc-3359-4ea1-bfb7-7bb5d4762963"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "2a9874d9-5c7e-414f-8959-1364f177aa84"}), (b:KNode {id: "07ff1a0b-e84f-40bb-996f-467a03d2bf3c"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "d46fb5c1-449d-4561-a399-93d8ec8b543f"}), (b:KNode {id: "1bdc520d-6211-4371-8ff0-2e7b3041aea4"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "1bdc520d-6211-4371-8ff0-2e7b3041aea4"}), (b:KNode {id: "04475552-1433-4e6d-92f9-a44406c7ed18"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "04475552-1433-4e6d-92f9-a44406c7ed18"}), (b:KNode {id: "440e4d3d-ea9f-4915-97e6-2b6b7c09c6c4"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 0;

MATCH (a:KNode {id: "04475552-1433-4e6d-92f9-a44406c7ed18"}), (b:KNode {id: "579fa81e-4a5a-4521-98d9-ea8b69a48e8d"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 1;

MATCH (a:KNode {id: "04475552-1433-4e6d-92f9-a44406c7ed18"}), (b:KNode {id: "65cecd50-0570-42ca-bf41-6b5ad967a0cf"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 2;

MATCH (a:KNode {id: "04475552-1433-4e6d-92f9-a44406c7ed18"}), (b:KNode {id: "d01f2da8-c079-4665-b0cf-cd78f5c9727e"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 3;

MATCH (a:KNode {id: "04475552-1433-4e6d-92f9-a44406c7ed18"}), (b:KNode {id: "6281d965-093e-4aaa-9ce0-2f67b95c8bbc"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 4;

MATCH (a:KNode {id: "04475552-1433-4e6d-92f9-a44406c7ed18"}), (b:KNode {id: "508419e1-a1ea-4863-82b7-3636e39e5ee4"})
MERGE (a)-[r:GROUPS]->(b)
SET r.position = 5;

MATCH (a:KNode {id: "2a05068f-d48c-4fdd-915c-778bc8f42211"}), (b:KNode {id: "24309c9a-2e80-47b9-884b-cc9801178c0d"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "24309c9a-2e80-47b9-884b-cc9801178c0d"}), (b:KNode {id: "371342c0-401f-4d34-a537-439386bf9f7c"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "371342c0-401f-4d34-a537-439386bf9f7c"}), (b:KNode {id: "42292902-3874-4d54-87ec-0e1b7362af13"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "499ff1af-eed7-425d-9fed-e357ec2e0b97"}), (b:KNode {id: "9d406912-c737-416c-94f2-4edb90db3ee7"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "9d406912-c737-416c-94f2-4edb90db3ee7"}), (b:KNode {id: "1e650360-f987-42c8-ab37-d2e928b82b32"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "1e650360-f987-42c8-ab37-d2e928b82b32"}), (b:KNode {id: "7bd2455a-1fe5-4972-9c36-78d6a4f0df9b"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "7bd2455a-1fe5-4972-9c36-78d6a4f0df9b"}), (b:KNode {id: "9e9629bd-eb94-40fc-ba6e-922420cd13f7"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "f776b280-d6fa-4bbd-b213-4978165137eb"}), (b:KNode {id: "08113955-1ff0-4131-877e-4466e614bd1b"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "08113955-1ff0-4131-877e-4466e614bd1b"}), (b:KNode {id: "bb00a29b-d851-4395-9e20-bce895bb379e"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "39b82207-e234-4352-bc3c-01d84362a7eb"}), (b:KNode {id: "5da0c374-473b-40d6-a7dd-659dc4f5211d"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "5da0c374-473b-40d6-a7dd-659dc4f5211d"}), (b:KNode {id: "0fa7348d-69f2-487a-a684-71eada16a96d"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "1497eefc-aa3d-4444-a426-9ccb0410b0bf"}), (b:KNode {id: "ff7c99b6-ce1f-4973-9d3c-89f1f12a1f69"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "ff7c99b6-ce1f-4973-9d3c-89f1f12a1f69"}), (b:KNode {id: "f1504ef9-d65e-4753-8032-27672b2ffa6a"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "f1504ef9-d65e-4753-8032-27672b2ffa6a"}), (b:KNode {id: "c6d131b8-0ba5-4ab4-bfdb-c871b95b98e6"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "440e4d3d-ea9f-4915-97e6-2b6b7c09c6c4"}), (b:KNode {id: "579fa81e-4a5a-4521-98d9-ea8b69a48e8d"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "579fa81e-4a5a-4521-98d9-ea8b69a48e8d"}), (b:KNode {id: "65cecd50-0570-42ca-bf41-6b5ad967a0cf"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "65cecd50-0570-42ca-bf41-6b5ad967a0cf"}), (b:KNode {id: "d01f2da8-c079-4665-b0cf-cd78f5c9727e"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "d01f2da8-c079-4665-b0cf-cd78f5c9727e"}), (b:KNode {id: "6281d965-093e-4aaa-9ce0-2f67b95c8bbc"})
MERGE (a)-[:NEXT]->(b);

MATCH (a:KNode {id: "6281d965-093e-4aaa-9ce0-2f67b95c8bbc"}), (b:KNode {id: "508419e1-a1ea-4863-82b7-3636e39e5ee4"})
MERGE (a)-[:NEXT]->(b);
